# Build
FROM node:20-alpine AS builder
WORKDIR /app

# Copia apenas os arquivos necessários para instalar dependências
COPY package.json package-lock.json ./
RUN npm install

# Copia o restante do código do frontend
COPY . .

# Build do Next.js
RUN npm run build

# Produção
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production

# Copia apenas os arquivos necessários para rodar a aplicação
COPY --from=builder /app/.next .next
COPY --from=builder /app/public ./public
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/node_modules ./node_modules

EXPOSE 3000

# Use next start para produção
CMD ["npx", "next", "start"]